version: "3.8"
services:
  airflow-webserver:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    env_file:
      - deployment/.env
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
    command: webserver
    depends_on:
      - airflow-scheduler

  airflow-scheduler:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    env_file:
      - deployment/.env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
    command: scheduler
